### ISSUE TITLE
[HEAD ISSUE] Refactoring

### ISSUE THREAD

**Issue by drblaui** [drblaui/cookie-clicker-autobuy#28]
This issue is only to provide a checklist to the milestone

- [x] switch to HTML Templating #21 
- [x] Cache Scroll Position in Buying Timeline #20 
- [x] Calculate Prices with discounts #24 
- [x] Fix timeline sorting #26 
- [x] adjust name text size dynamically #27 
- [x] Change Slider #29 
- [x] switch `document.getElementById()` to cookie clicker build in `l('ID')`
- [x] If all buying is turned off, remove the next buy container
- [x] look for other cookie clicker functions (like binding click event listeners) and implement them (unnecessary)
- [x] consider moving some functions out of mod context scope into global scope for easier access (unnecessary)
- [x] use Game.Version on Image strings, so these dynamically scale with the game

**Comment by drblaui** [comment]
Honestly, the code runs smoothly (as smoothly as JS can run), so some things aren't necessariy
